spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sprout_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: true
  flyway:
    enabled: true
jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION_MS:86400000} # 24 hours
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_MS:120960000} # 14 days
openai:
  secret-key: ${OPENAI_SECRET_KEY}

---

# Sqs 프로파일 설정

spring:
  config:
    activate:
      on-profile: sqs
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      credentials:
        secret-key: ${sqs.secret-key}
        access-key: ${sqs.access-key}