spring:
  application:
    name: backend
  config:
    import: application-secret.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/sprout_db
    username: secret
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect