spring:
  application:
    name: backend
  config:
    import: application-secret.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/sprout_db
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret: ${jwt.secret}
  access-expiration: ${jwt.expiration-ms}
  refresh-expiration: ${jwt.refresh-expiration-ms}